---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt
spec:
  acme:
    email: roshen@ideabits.se
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: issuer-account-private-key
    solvers:
      - http01:
          gatewayHTTPRoute:
            parentRefs: # This is the name of the Gateway that will be created in the next step
              - name: blog-gateway
                namespace: blog
                kind: Gateway
