apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: http-filter-redirect
  namespace: blog
spec:
  parentRefs:
    - name: blog-gateway
      sectionName: http
  hostnames:
    - roshenrumy.com
  rules:
    - filters:
        - type: RequestRedirect
          requestRedirect:
            scheme: https
            statusCode: 301
