---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: cert-manager
  namespace: flux-system
spec:
  dependsOn:
    - name: crds
  interval: 10m0s
  path: ./cert-manager-controller
  prune: true
  sourceRef:
    kind: GitRepository
    name: roshenrumy-com
  timeout: 2m0s
  wait: true
