---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: crds
  namespace: flux-system
spec:
  interval: 10m0s
  path: ./k8s/base/crds
  prune: true
  sourceRef:
    kind: GitRepository
    name: roshenrumy-com
  timeout: 2m0s
  wait: true
