---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: roshenrumy-com
  namespace: flux-system
spec:
  interval: 1m0s
  ref:
    branch: main
  url: ssh://git@github.com/roshenrumy/roshenrumy.com
  secretRef:
    name: flux-git-ssh-key
