---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prod
  namespace: flux-system
spec:
  dependsOn:
  - name: crds
  interval: 5m0s
  path: ./k8s/overlays/prod
  prune: true
  sourceRef:
    kind: GitRepository
    name: roshenrumy-com
  timeout: 2m0s
  wait: true
