apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base/resources/gateway-fabric
  - ../../base/resources/namespace
  - ../../base/resources/db
  - ../../base/resources/be
  - ../../base/resources/fe

commonLabels:
  environment: local
