apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: blog-gateway
  namespace: blog
spec:
  gatewayClassName: nginx
  listeners:
    - name: http
      port: 80
      protocol: HTTP
