apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-persistent-volume
  namespace: blog
  labels:
    type: local
    app: postgres
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /mnt/data/postgres
